baseURL = "https://www.darrenlyons.me/"
languageCode = "en-us"
title = "Darren Lyons"
theme = "ananke"
uglyurls = true
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = "https://twitter.com/darren_lyons"
  instagram = ""
  youtube = ""
  github = "https://github.com/darrenjl"
  linkedin = "https://www.linkedin.com/in/darrenlyons/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "dark-blue"
